# Generated by Django 2.2 on 2021-02-02 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateTimeField()),
                ('gender', models.CharField(max_length=10)),
                ('grade', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_content', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('msg_UsrJoin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usermessages_join', to='group_app.User')),
                ('user_likes', models.ManyToManyField(related_name='liked_posts', to='group_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('max_capacity', models.IntegerField()),
                ('action_enrolled', models.CharField(max_length=10)),
                ('action_class_full', models.CharField(max_length=10)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=5)),
                ('child_event', models.ManyToManyField(related_name='enrolled_child', to='group_app.Child')),
                ('user_event', models.ManyToManyField(related_name='enrolled_user', to='group_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_content', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('com_UserJoin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercomments_join', to='group_app.User')),
                ('msg_CommJoin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msgcomments_join', to='group_app.Message')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='parent_child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_parent', to='group_app.User'),
        ),
    ]
