# Generated by Django 3.1.4 on 2021-02-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='action_enrolled',
        ),
        migrations.AddField(
            model_name='event',
            name='current_enrolled',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='action_class_full',
            field=models.BooleanField(default=False),
        ),
    ]
