# Generated by Django 3.1.4 on 2021-02-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='action_class_full',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='action_enrolled',
            field=models.BooleanField(default=False),
        ),
    ]
