# Generated by Django 2.2 on 2021-01-31 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateTimeField()),
                ('gender', models.CharField(max_length=10)),
                ('grade', models.IntegerField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_parent', to='group_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('user', models.CharField(max_length=250)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('max_capacity', models.IntegerField(max_length=100)),
                ('action_enrolled', models.CharField(max_length=10)),
                ('action_class_full', models.CharField(max_length=10)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=5)),
                ('child_EvtJoin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ChildEvents_join', to='group_app.Child')),
                ('child_event', models.ManyToManyField(related_name='enrolled_child', to='group_app.Child')),
                ('user_event', models.ManyToManyField(related_name='enrolled_user', to='group_app.User')),
            ],
        ),
    ]
