# Generated by Django 2.2 on 2021-02-04 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='age',
        ),
    ]
