# Generated by Django 2.2 on 2021-02-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_app', '0002_remove_child_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='age',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
