# Generated by Django 3.1.4 on 2021-02-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_app', '0002_auto_20210203_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='action_enrolled',
        ),
        migrations.AddField(
            model_name='event',
            name='current_enrolled',
            field=models.IntegerField(default=0),
        ),
    ]
