# Generated by Django 2.2 on 2021-02-05 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_app', '0003_child_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_date',
        ),
    ]
